# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.xll: error
    org.springframework: error

spring:
  validation:
    apply-default-config: true
  application:
    name: xll-frameworks-pro-web
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
#      config:
#        server-addr: ${spring.cloud.nacos.discovery.server-addr}
#        file-extension: yml
#        shared-configs:
#          - application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}

# Dubbo Protocol
dubbo:
  protocol:
    name: dubbo
    ## Random port
    port: -1

  ## Dubbo Registry
  registry:
    address: nacos://127.0.0.1:8848/?username=nacos&password=nacos

## DemoService version
demo:
  service:
    version: 1.0.0


# feign 配置
feign:
  sentinel:
    enabled: true
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
  compression:
    request:
      enabled: true
    response:
      enabled: true